version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file: ./config.ini
    ports:
      - '5432:5432'
    container_name: resource_manager_db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./config.ini
    image: resource_manager_image
    container_name: resource_manager
